---
title: "In class Aug 20"
author: "Beth Babcock"
date: "`r Sys.Date()`"
output: html_document
---

Look at the file called RStudio_Git_Cheatsheet for all the things you can do in the git panel in RStudio.

#### 1. Work with an existing repository

- Finish the Week 1 technology check

- Look in the class repository on GitHub and in the desktop. I will make a new folder in module 2 called “In_class_exercise”

- Pull the repository, open the folder, and make a new R script in the folder called YourName_module2.r.

- the R code, make a summary of bruv.csv, and plot of bruv.csv. Commit and push your new code.

#### 2. Make your own repository

- Use the tutorial called Exercise Github Setup to make your own private repository

- invite the professor @ebabcock

- From now on, keep your code in your GitHub folder, and push it so that I can look at it when you turn something in.

#### 3. Put some code in your repository and push

- Copy the file InClassExampleModule2.r and the bruv.csv file into your new repository.

- Make some changes to the code, e.g. to change the look of the figure.

- Push the revised file

#### 4. Pull revised code.

- Fetch and pull the repository again, and respond to the changes the professor put in the file.

#### 5. Branching and resolving conflicts

- Do the branching tutorial. After you finish this, make a conflict to see how this works.  

- In your add-notes branch, make a change in a line of the readme file, and commit. 

- Make a different change in the *same* line of the readme file in main on your computer. Commit and push. 

- On the website, do a merge request to merge add-notes into main.  Resolve any conflicts that come up.  

#### Prepare for Module 3 on exponential growth

- If you are out of practice with logarithms and exponents, do the bonus tutorial

- Feel free to read the book chapter, included with module 3. 

