---
title: "Questions on exponential growth"
author: "Elizabeth A. Babcock"
format: html
editor: visual
---

```{r,message=FALSE}
library(tidyverse)
```

Recalling that for continuous time (t can be any real positive number)

$N_t=N_0e^{r_m t}$

$log(N_t)=log(N_0)+r_m*t$

and for a annual time step (t is integer years or days)

$N_t=N_0\lambda^t$

Where

$\lambda=e^{r_m}$

### Neal: Introduction to Population Biology question 4.1.

Each individual of an annual plant species produces on average ten seeds. (a) Starting with a single individual, what will be the population size after 6 years, assuming all the seeds survive to produce adult plants the following generation? (b) A new variety of the plant produces 5 per cent more seeds, i.e. 10.5 seeds on average. What will be the potential number of offspring after 6 years from a single individual?

Answer: N0 is 1.0, because the problem says that we have one plant at the beginning. lambda is 10. It is the number we multiply by to get next year's population from this years. For each plant one year, we will have 10 plants next year (10 seeds, minus one death of the original plant, is 10) So in six years, we get 10\^6 plants.

It we have an average of 10.5 seeds, the answer is Nt=(1)\*(10.5)\^6 = 1340096.

### Neal: Introduction to Population Biology question 4.2.

The Norway rat breeds continuously and has an estimated rate of natural increase (rm) of 0.0143 per day. A small number invade a garbage dump where living conditions are ideal. How long will it take the population to double in size?

Nt/N0 = 2 2 = e\^0.0143t

ln(2) = 0.0143t log(2)/0.0143 = 48.47183 = 48.5

The Norway rat population will take approximately 48.5 days to double in size.

### Neal: Introduction to Population Biology question 4.5.

A population increases fivefold over a 4-week period. What is the value of $\lambda$ per day, assuming exponential growth?

4\*7 = 28 days

5 = lambda\^28

5\^(1/28)

lambda = 1.059164
